language: go
sudo: false
go:
  - 1.5.2
  - tip

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/gorilla/websocket
  - go get github.com/gin-gonic/gin
  - go get github.com/rs/xid
  - go get gopkg.in/redis.v3
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken QlO06wVQ0qmjGiTU79yUWgKP97zLrsf62
